# Generated by Django 5.1.3 on 2024-11-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptrent', '0002_userprofile_solicitudarriendo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nombres',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
