# Generated by Django 5.1.3 on 2024-11-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptrent', '0003_userprofile_apellidos_userprofile_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='apellidos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nombres',
            field=models.CharField(max_length=100),
        ),
    ]
